/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package librarysystem.UI;

import java.util.List;
import librarysystem.Data;
import librarysystem.Entities.Member;

/**
 *
 * @author Pramod
 */
public class FindMember extends javax.swing.JPanel {
    
    boolean filled;
    /**
     * Creates new form FindMember
     */
    public FindMember() {
        initComponents();
        filled =false;
    }
    
    public void setMembers(List<Member> members){
        clearMembers();
        
        for(Member mem: members){
            findMemberByName.addItem(mem.getFullName());
            findMemberbyId.addItem(mem.getMemberId());
        }

        repaint();
        revalidate();
        filled =true;
       
    }
    public void clearMembers(){
        filled =false;
        findMemberByName.removeAllItems();
        findMemberbyId.removeAllItems();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        findMemberbyId = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        findMemberByName = new javax.swing.JComboBox();

        setBorder(javax.swing.BorderFactory.createTitledBorder("FInd Memer"));

        jLabel1.setText("By Id:");

        findMemberbyId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findMemberbyIdActionPerformed(evt);
            }
        });

        jLabel2.setText("By Name:");

        findMemberByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findMemberByNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(findMemberbyId, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(findMemberByName, 0, 208, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findMemberbyId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findMemberByName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void findMemberbyIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findMemberbyIdActionPerformed
        // TODO add your handling code here:
        if(filled==true)
            findMemberByName.setSelectedIndex(findMemberbyId.getSelectedIndex());
    }//GEN-LAST:event_findMemberbyIdActionPerformed

    private void findMemberByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findMemberByNameActionPerformed
        // TODO add your handling code here:
        if(filled==true)
            findMemberbyId.setSelectedIndex(findMemberByName.getSelectedIndex());
    }//GEN-LAST:event_findMemberByNameActionPerformed
    
    public Member getSelectedMember(){
        return Data.members.get(findMemberbyId.getSelectedIndex());
    }
    public void setSelectedMember(Member member){
        findMemberByName.setSelectedItem(member);
        findMemberbyId.setSelectedItem(member.getMemberId());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox findMemberByName;
    private javax.swing.JComboBox findMemberbyId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
