/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarysystem.UI;

import java.util.List;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import librarysystem.Data;
import librarysystem.Entities.Address;
import librarysystem.Entities.Author;
import librarysystem.Entities.Book;
import librarysystem.Entities.Copy;
import librarysystem.Entities.Magazine;
import librarysystem.Entities.Member;
import librarysystem.Entities.Publication;

/**
 *
 * @author Pramod
 */
public class LoanTab extends javax.swing.JPanel {

    /**
     * Creates new form FunctionsTab
     */
    List<Author> authors;
    List<Book> books;
    List<Member> members;
    List<Address> address;
    List<Magazine> magazines;
    boolean memberFilled;
    boolean publicationComboFilled;
    JTabbedPane functionTab;

    public LoanTab() {
        initComponents();
        authors = Data.authors;
        books = Data.books;
        members = Data.members;
        magazines = Data.magazines;
        address = Data.address;
        publicationComboFilled = false;
        //initLoanPanel();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        findMemPanel = new librarysystem.UI.FindMember();
        jPanel22 = new javax.swing.JPanel();
        bookRadio = new javax.swing.JRadioButton();
        magazineRadio = new javax.swing.JRadioButton();
        publicationCombo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        numberOfCopies = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        reserveButton = new javax.swing.JButton();
        loanButton = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        copyTable = new javax.swing.JTable();
        publicationTitle = new javax.swing.JTextField();

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder("Pulication"));

        buttonGroup1.add(bookRadio);
        bookRadio.setText("Book");
        bookRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(magazineRadio);
        magazineRadio.setText("Magazine");
        magazineRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                magazineRadioActionPerformed(evt);
            }
        });

        publicationCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publicationComboActionPerformed(evt);
            }
        });

        jLabel5.setText("Item:");

        jLabel6.setText("Available Copies:");

        numberOfCopies.setEditable(false);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(bookRadio)
                .addGap(93, 93, 93)
                .addComponent(magazineRadio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(publicationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberOfCopies, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookRadio)
                    .addComponent(magazineRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(publicationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(numberOfCopies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions"));

        reserveButton.setText("Reserve");
        reserveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveButtonActionPerformed(evt);
            }
        });

        loanButton.setText("Loan");
        loanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(reserveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveButton)
                    .addComponent(loanButton))
                .addContainerGap())
        );

        copyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Copy No.", "Status", "Loaned to", "CheckOut Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(copyTable);

        publicationTitle.setEditable(false);
        publicationTitle.setText("Publication-Title");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(findMemPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(publicationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(publicationTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(findMemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRadioActionPerformed

        publicationComboFilled = false;
        publicationCombo.removeAllItems();
        for (Book p : books) {
            publicationCombo.addItem(p);
        }
        publicationComboFilled = true;
        Publication publication = (Publication) publicationCombo.getItemAt(0);
        selectAction(publication);
    }//GEN-LAST:event_bookRadioActionPerformed

    private void magazineRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_magazineRadioActionPerformed

        publicationComboFilled = false;
        publicationCombo.removeAllItems();

        for (Magazine p : magazines) {
            publicationCombo.addItem(p);
        }
        publicationComboFilled = true;
        Publication publication = (Publication) publicationCombo.getItemAt(0);
        selectAction(publication);
    }//GEN-LAST:event_magazineRadioActionPerformed

    private void publicationComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publicationComboActionPerformed
        // TODO add your handling code here:
        if (publicationComboFilled) {
            Publication publication = (Publication) publicationCombo.getSelectedItem();
            selectAction(publication);
        }
    }//GEN-LAST:event_publicationComboActionPerformed

    private void reserveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveButtonActionPerformed
        Publication publication = (Publication) publicationCombo.getSelectedItem();
        Member reserver = findMemPanel.getSelectedMember();
        reserver.reserve(publication);
        
        functionTab =(JTabbedPane)this.getParent();      
        functionTab.setSelectedIndex(2);
        ReservationTab reservationTab =(ReservationTab) functionTab.getComponent(2);
        reservationTab.initialize();
        reservationTab.populateComponents(reserver);
        //reservationTab.populateComponents(reserver);
    }//GEN-LAST:event_reserveButtonActionPerformed

    private void loanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanButtonActionPerformed
        // TODO add your handling code here:
        Member loaner = findMemPanel.getSelectedMember();
        Publication publication = (Publication) publicationCombo.getSelectedItem();
        loaner.loan(publication.getAcopy());
        selectAction(publication);
        
        functionTab =(JTabbedPane)this.getParent();
        ReturnTab res =(ReturnTab) functionTab.getComponent(1);
        res.initialize();
        

        
    }//GEN-LAST:event_loanButtonActionPerformed
public void initLoanPanel() {
        findMemPanel.setMembers(members);
        bookRadio.setSelected(true);
        bookRadioActionPerformed(null);
        Publication publication = (Publication) publicationCombo.getItemAt(0);
        selectAction(publication);
    }

    public void selectAction(Publication publication) {
        
        numberOfCopies.setText("" + publication.getAvailNumCopy() + "");
        if (publication. getAvailNumCopy() >= 1) {
            loanButton.setEnabled(true);
            reserveButton.setEnabled(false);
        } else {
            loanButton.setEnabled(false);
            reserveButton.setEnabled(true);
        }

        publicationTitle.setText(publication.getTitle());
        DefaultTableModel defaultModel = (DefaultTableModel) copyTable.getModel();
        defaultModel.setRowCount(0);
        for (Copy copy : publication.getCopies()) {
            defaultModel.addRow(copy.getVector());
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bookRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable copyTable;
    private librarysystem.UI.FindMember findMemPanel;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton loanButton;
    private javax.swing.JRadioButton magazineRadio;
    private javax.swing.JTextField numberOfCopies;
    private javax.swing.JComboBox publicationCombo;
    private javax.swing.JTextField publicationTitle;
    private javax.swing.JButton reserveButton;
    // End of variables declaration//GEN-END:variables
}
